### ISSUE TITLE
Feature request: specify extra headers when connecting

### ISSUE THREAD

**Issue by mcseemk** [1tgr/rust-websocket-lite#12]
Some WS servers require extra headers to be set at upgrade connection request (like Authorization , etc). Currently there is no way to specify them.

One way to do it would be to add something like add_header(name: String, value: String) method to ClientBuilder to create a vec or hashmap of extra headers which will then be added to the upgrade request by build_request() function.

**Comment by 1tgr** [comment]
Agree, I think it can live as a `Vec<(String, String)>` inside `ClientBuilder`. We're not treating `ClientBuilder` as performance sensitive so `Vec` allocation and `String` cloning is OK here.

There are [types for HTTP headers](https://docs.rs/http/0.1.20/http/header/index.html) more sophisticated than pairs of strings, but I don't think there's a strong need to use them here.

**Comment by 1tgr** [comment]
Closed by #15.
