### ISSUE TITLE
Update tokio-util dependency

### ISSUE THREAD

**Issue by ljedrz** [1tgr/rust-websocket-lite#273]
Is this repository still maintained? I forked it, as I needed current `tokio-util` in order for it to work with my project, but I wonder if the current inactivity is temporary or not. There aren't any extra features I'm currently interested in, so I'm talking about passive maintenance (updating deps, bugfixes).

**Comment by 1tgr** [comment]
I haven't been clicking the button that merges Dependabot's PRs that update dependencies, but if you have a PR I'd be happy to merge it into this repo.

As it happens I'm away from day-to-day Rust development but I'm happy to step in as needed.

**Comment by ljedrz** [comment]
I just checked and https://github.com/1tgr/rust-websocket-lite/pull/270 (which also covers https://github.com/1tgr/rust-websocket-lite/pull/259) is basically all I'd need right now; not sure why 2 CI jobs are failing there, are they perhaps flaky or is there anything that would require some extra work?

**Comment by 1tgr** [comment]
The error on integration testing is a connection reset at the end, which I've seen before sometimes. The error went away on a rerun.

The error on fuzz testing looks the same as signalapp/libsignal#378. Hopefully an update to the nightly toolchain will fix it, I'm trying it locally.

**Comment by 1tgr** [comment]
https://github.com/1tgr/rust-websocket-lite/blob/beb66a58c40cfdbd34c52ae5ce6bca88bf9db7b7/rust-nightly-toolchain#L1

Happy birthday!

**Comment by ljedrz** [comment]
Thanks, it looks like for the time being I can just depend on the `master` branch of the repo now, which is totally fine for me :ok_hand:.

**Comment by 1tgr** [comment]
On second thoughts, I'll update the crates to reference tokio-util >= 0.6, thereby allowing 0.6 or 0.7 (or 0.8 etc). The repo builds fine with either version, although I notice tokio-util adds tokio-rs/tokio#4427 which I asked for a while back.
