### ISSUE TITLE
websocket-lite codec assumes that HTTP headers are case-sensitive, but they are not

### ISSUE THREAD

**Issue by mcseemk** [1tgr/rust-websocket-lite#8]
As per RFC 7230 https://tools.ietf.org/html/rfc7230#section-3.2 HTTP/1.1 headers are case-insensitive, however, websocket-lite codec uses hardcoded 'Sec-WebSocket-Accept' header name and fails connection when given, say, 'sec-websocket-accept' header in the server reply.

**Comment by 1tgr** [comment]
Thanks!
