### ISSUE TITLE
Websocket protocol upgrade failed in firefox

### ISSUE THREAD

**Issue by fengyc** [1tgr/rust-websocket-lite#85]
Firefox sends header `Connection: keep-alive, Upgrade`, that the `check_header` function could not handle.

https://github.com/1tgr/rust-websocket-lite/blob/de4b4a60dbb6b9cbbc8e8702e602f71d1cb5d243/websocket-codec/src/upgrade.rs#L73-L88

`actual.eq_ignore_ascii_case(expected)` should be replaced with `containsXXX`.

**Comment by 1tgr** [comment]
Thanks! This is the standard Firefox websocket client talking to the Rust server?

**Comment by fengyc** [comment]
Yes, the latest firefox 77.0.1.

**Comment by 1tgr** [comment]
I pushed a change to the `firefox` branch that fixes it for me. Are you able to test it on the branch before I make a release to crates.io?

**Comment by fengyc** [comment]
Tested. Works for me.

**Comment by 1tgr** [comment]
Pushed: https://crates.io/crates/websocket-lite/0.3.5
